[package]
name = "laser-web"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { workspace = true, features = ["default_fonts", "glow"] }
laser-app.workspace = true
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Document", "HtmlCanvasElement", "MediaQueryList", "Window"] }
